apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../../base
- ../../crds
- github.com/argoproj/argo-cd/manifests/cluster-rbac?ref=v1.8.3
- applications
- projects
- secrets/auth/dex-server-sa.yaml
configMapGenerator:
- name: argocd-cm
  behavior: replace
  files:
  - configs/argo_cm/dex.config
  - configs/argo_cm/configManagementPlugins
  - configs/argo_cm/globalProjects
  envs:
  - configs/argo_cm/envs
- name: argocd-rbac-cm
  behavior: replace
  files:
  - configs/argo_rbac_cm/policy.csv
generatorOptions:
  disableNameSuffixHash: true
generators:
- secrets/gpg/secret-generator.yaml
- secrets/clusters/secret-generator.yaml
patchesStrategicMerge:
- serviceaccounts/argocd-dex-server.yaml
- secrets/auth/argocd-secret.yaml
